theme: jekyll-theme-slate  #minima
title: "maximal"
description: "A TensorFlow-compatible Python library that provides models and layers to implement custom Transformer neural networks. Built on TensorFlow 2."
