theme: minima
title: "maximal Official Documentation"
description: "A TensorFlow-compatible Python library that provides models and layers to implement custom Transformer neural networks. Built on TensorFlow 2."
